name: base
channels:
  - conda-forge
dependencies:
  - numpy==1.26.4
  - numba
  - pip:
      - affine==2.4.0
      - aicspylibczi==3.1.2
      - aiobotocore==2.13.0
      - aiohttp==3.9.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - alphabase==1.2.4
      - asciitree==0.3.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.83
      - botocore==1.34.106
      - cellpose==3.0.8
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorama==0.4.6
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.5.1
      - dask-expr==1.1.1
      - distributed==2024.5.1
      - fasteners==0.19
      - fastremap==1.14.1
      - filelock==3.14.0
      - fonttools==4.52.4
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - h5py==3.11.0
      - hilbertcurve==2.0.5
      - idna==3.7
      - imagecodecs==2024.1.1
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - llvmlite==0.42.0
      - locket==1.0.0
      - lxml==5.2.2
      - mahotas==1.4.15
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - natsort==8.4.0
      - networkx==3.3
      - numcodecs==0.12.1
      - ome-zarr==0.9.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - packaging==24.0
      - pandas==2.2.2
      - partd==1.4.2
      - pillow==10.3.0
      - psutil==5.9.8
      - pyahocorasick==2.1.0
      - pyarrow==16.1.0
      - pyparsing==3.1.2
      - pyteomics==4.7.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.5
      - pytz==2024.1
      - pyyaml==6.0.1
      - rasterio==1.3.10
      - regex==2024.5.15
      - requests==2.32.3
      - roifile==2024.5.24
      - s3fs==2024.5.0
      - scikit-fmm==2024.5.29
      - scikit-image==0.23.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - shapely==2.0.4
      - six==1.16.0
      - snuggs==1.4.7
      - sortedcontainers==2.4.0
      - svgelements==1.9.6
      - sympy==1.12.1
      - tabulate==0.9.0
      - tblib==3.0.0
      - threadpoolctl==3.5.0
      - tifffile==2024.5.22
      - toolz==0.12.1
      - torch==2.3.0
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.0
      - tornado==6.4
      - tqdm==4.66.4
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zarr==2.18.2
      - zict==3.0.0
      - zipp==3.19.0
      - xarray==2024.5.0