# This is a basic workflow to help you get started with Actions

name: Build Documentation

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Dependencies with Mamba
      run: |
        conda env update -n base --file .github/additional_files/environment.yml
    - name: Install Repository Module
      run: |
        pip install ./
